defaults:
  - agent: mdp_goal # can be mdp_goal or mdp_prompt
  - override hydra/launcher: submitit_local

# task settings
task: walker_walk
discount: 0.99
# train settings (Not relevant for eval)
num_grad_steps: 500000
log_every_steps: 1000
# eval
eval_every_steps: 10000
num_eval_episodes: 100
# snapshot
snapshot_ts: 100000
snapshot_base_dir: snapshots
# dataset
batch_size: ${agent.batch_size}

# goal loader dataset
goal_buffer_dir: /home/matias_rodriguez/maskdp-taskgeneral/maskdp_data/maskdp_train
goal_buffer_size: 100000000
goal_buffer_num_workers: 4

# misc
seed: 1
device: cuda
save_video: true
use_tb: false # Nope
use_wandb: true
project: mdp-eval
notes: "finetune"
replan: false


hydra:
  run:
    dir: "/home/matias_rodriguez/maskdp-taskgeneral/maskdp_models/${exp_name}/${now:%Y.%m.%d}/${now:%H%M%S}_${agent.name}"
