# @package agent
_target_: agents.policies.mdpActorCustomPPO.MDPWrapperPPO
name: MDPWrapperPPO
obs_shape: ??? 
action_shape: ??? 
device: ${device}
lr: 1e-4
use_tb: ${use_tb}
batch_size: 1024 
mask_ratio: [0.15, 0.35, 0.55, 0.75, 0.95]
pretrained: true
transformer_cfg:
  n_embd: 128 #128 
  n_head: 2
  n_enc_layer: 1
  n_dec_layer: 1
  embd_pdrop: 0
  resid_pdrop: 0
  attn_pdrop: 0
  traj_length: 128
  pe: 'fixed'
  loss: 'total'
  norm: 'l2'
  zero_pad_prob: 0.2
  initial_std: 0.04
  clip_coef: 0.08
  ent_coef: 0.3
  weights_path: '/home/matias_rodriguez/maskdp-taskgeneral/snapshots/unsup_snap_200000_1.pt'